import { z } from "zod";

const createSettingValidationSchema = z.object({
  body: z.object({
    metaDescription: z.string().optional(),
    description: z.string().optional(),
    privacy: z.string().optional(),
    terms: z.string().optional(),
    orderPolicy: z.string().optional(),
    logo: z.string().optional(),
    favicon: z.string().optional(),
    lotoImg: z.string().optional(),
    metaImg: z.string().optional(),
    title: z.string().optional(),
    bgColor: z.string().optional(),
    country: z.string().optional(),
    currencySymbol: z.string().optional(),
    copyright: z.string().optional(),
    deliveryMethod1: z.string().optional(),
    deliveryMethod2: z.string().optional(),
    pickupMethod1: z.string().optional(),
    pickupMethod2: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentText1: z.string().optional(),
    paymentText2: z.string().optional(),
    officeAddress: z.string().optional(),
    whatsApp: z.number().optional(),
    telegram: z.string().optional(),
    kindlyNote: z.string().optional(),
    order: z.string().optional(),
    orderText: z.string().optional(),
  }),
});
const updateSettingValidationSchema = z.object({
  body: z.object({
    metaDescription: z.string().optional(),
    description: z.string().optional(),
    privacy: z.string().optional(),
    terms: z.string().optional(),
    orderPolicy: z.string().optional(),
    logo: z.string().optional(),
    favicon: z.string().optional(),
    lotoImg: z.string().optional(),
    metaImg: z.string().optional(),
    title: z.string().optional(),
    bgColor: z.string().optional(),
    country: z.string().optional(),
    currencySymbol: z.string().optional(),
    copyright: z.string().optional(),
    deliveryMethod1: z.string().optional(),
    deliveryMethod2: z.string().optional(),
    pickupMethod1: z.string().optional(),
    pickupMethod2: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentText1: z.string().optional(),
    paymentText2: z.string().optional(),
    officeAddress: z.string().optional(),
    whatsApp: z.number().optional(),
    telegram: z.string().optional(),
    kindlyNote: z.string().optional(),
    order: z.string().optional(),
    orderText: z.string().optional(),
  }),
});

export const settingValidations = {
  createSettingValidationSchema,
  updateSettingValidationSchema,
};
